config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers
  authenticated :teacher do
    root to: "teachers#dashboard", as: :authenticated_root
  end

  namespace :admin do
    resources :teachers
  end

  root to: "teachers#dashboard"

  resources :documents, only: [ :create, :show, :destroy ]
  get "share/:slug", to: "documents#share_document", as: :share_document

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  VALID_FILE_TYPES = %w[text/markdown]
  belongs_to :teacher
  has_one_attached :file

  validates :title, presence: true
  validates :file, presence: true
  validate :validate_file_type

  before_create :generate_slug

  def self.build_from_params(params = {})
    model = Document.new(params)
    if model.valid?
      file = model.file
      subclass = subclass_for_file_type(file.content_type)
      subclass.new(params)
    else
      raise ArgumentError, model.errors.full_messages
    end
  end

  def shareable_url
    "/share/#{slug}"
  end

  def render_html
    raise NotImplementedError, "Document subclass must implement a render_html method!"
  end

  private

    def generate_slug
      self.slug = SlugGenerator.generate(title.to_s, Document)
    end

    def self.subclass_for_file_type(file_type)
      case file_type
      when "text/markdown"
        MarkdownDocument
      else
        Document
      end
    end

  def validate_file_type
    if file.attached? && !file.content_type.in?(VALID_FILE_TYPES)
      errors.add(:file, "must be a valid file type. Valid types: #{VALID_FILE_TYPES.join(", ")}")
    end
  end
end

app/models/markdown_document.rb
class MarkdownDocument < Document
  validate :markdown_file_type

  def render_html
    return "" unless file&.download
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, tables: true)
    markdown.render(file.download)
  end

  private

  def markdown_file_type
    errors.add(:file, "must be a Markdown file.") unless file.content_type == "text/markdown"
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :documents

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/teachers_controller.rb
class Admin::TeachersController < ApplicationController
  before_action :authenticate_teacher!
  before_action :authorize_admin!
  before_action :set_teacher, only: [ :edit, :update, :destroy ]

  def index
    @teachers = Teacher.all
  end

  def new
    @teacher = Teacher.new
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      respond_to do |format|
        set_flash(:success, "Teacher created successfully.")
        format.html { redirect_to admin_teachers_path }
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if teacher_params.empty?
      set_flash(:alert, "Please enter changes to update Teacher account")
      render :edit
    elsif @teacher.update(teacher_params)
      respond_to do |format|
        set_flash(:success, "Teacher updated successfully.")
        format.html { redirect_to admin_teachers_path }
      end
    else
      set_flash(:alert, @teacher.errors.full_messages)
      render :edit
    end
  end

  def destroy
    if @teacher == current_teacher
      respond_to do |format|
        format.html { redirect_to admin_teachers_path, alert: "You cannot delete your own account." }
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("flash", partial: "layouts/flash_messages")
        end
      end
    elsif @teacher.destroy
      respond_to do |format|
        format.html { redirect_to admin_teachers_path, notice: "Teacher deleted successfully." }
        format.turbo_stream do
          render turbo_stream: turbo_stream.remove(dom_id(@teacher))
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to admin_teachers_path, alert: "Failed to delete the teacher." }
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("flash", partial: "layouts/flash_messages")
        end
      end
    end
  end

  private

  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :email, :admin, :password, :password_confirmation).tap do |permitted|
      permitted.compact_blank!
    end
  end

  def authorize_admin!
    unless current_teacher.admin?
      redirect_to root_path, alert: "You do not have permission to access this page."
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def set_flash(type, message, now = nil)
    now ? flash.now[type] = message : flash[type] = message
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_teacher!, only: [ :create, :show ]
  before_action :set_document, only: [ :show, :destroy ]
  before_action :set_share_document, only: [ :share_document ]
  before_action :authorize_teacher!, only: [ :show ]

  def create
    @document = Document.build_from_params(document_params.merge(teacher_id: current_teacher.id))
    if @document.save
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Document uploaded successfully." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream
      end
    end
  rescue ArgumentError => e
    respond_to do |format|
      format.html do
        set_flash(:alert, e.message, now: true)
        redirect_to root_path
      end
      format.turbo_stream do
        set_flash(:alert, e.message, now: true)
        render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
      end
    end
  end

  def show
  end

  def destroy
    if current_teacher.admin? || @document.teacher == current_teacher
      @document.destroy
      respond_to do |format|
        format.turbo_stream do
          set_flash(:notice, "Document deleted successfully.", now: true)
          render turbo_stream: turbo_stream.remove(@document) +
            turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
        end
        format.html do
          redirect_to documents_path, notice: "Document deleted successfully."
        end
      end
    else
      respond_to do |format|
        format.turbo_stream do
          set_flash(:alert, "You do not have permission to delete this document.", now: true)
          render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
        end
        format.html do
          redirect_to root_path, alert: "You do not have permission to delete this document."
        end
      end
    end
  end

  def share_document
    if @document.nil?
      set_flash(:alert, "Sorry, the document you're looking for could not be found.")

      respond_to do |format|
        format.html { render "errors/not_found", status: :not_found }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("flash_messages", partial: "layouts/flash_messages")
        end
      end
    else
      render :show
    end
  end

  private

  def document_params
    params.require(:document).permit(:title, :file)
  end

  def set_share_document
    @document = Document.find_by(slug: params[:slug])
  end

  def set_document
    @document = Document.find(params[:id])
  end

  def authorize_teacher!
    unless current_teacher.admin? || current_teacher == @document.teacher
      set_flash(:alert, "You do not have permission to view this document.")
      redirect_to root_path
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :authenticate_teacher!, only: [ :dashboard ]
  def dashboard
    if teacher_signed_in?
      @teacher = current_teacher
      @documents = current_teacher.documents.order(created_at: :desc)
      @document = Document.new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/admin/teachers/_form.html.erb
<%= form_with(model: @teacher, url: locals[:form_path], method: locals[:method], class: "card flex flex-col gap", data: { turbo: false }) do |form| %>
  <% if @teacher.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @teacher.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "input" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "input" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "input" %>
  </div>

  <div class="form-group">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, class: "input" %>
    <% if locals[:method] == :put %>
      <small>Leave blank to keep current password</small>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "input" %>
  </div>

  <%= form.submit "Save", class: "btn btn--primary" %>
<% end %>

app/views/admin/teachers/_teacher.html.erb
<tr id="<%= dom_id(teacher) %>">
  <td><%= teacher.full_name %></td>
  <td><%= teacher.email %></td>
  <td><%= teacher.admin? ? 'Yes' : 'No' %></td>
  <td>
    <%= button_to 'Edit', edit_admin_teacher_path(teacher), method: :get, class: 'btn btn-warning' %>
    <%= button_to 'Delete', admin_teacher_path(teacher), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/teachers/_teachers.html.erb
<ul id="teachers">
  <%= render @teachers %>
</ul>

app/views/admin/teachers/edit.html.erb
<%
  @back_button ||= root_path
%>

<h1>Edit Teacher</h1>

<%= render "form", locals: { form_path: admin_teacher_path(@teacher), method: :put }%>

<%= link_to 'Back to list', admin_teachers_path, class: 'btn btn-secondary' %>

app/views/admin/teachers/index.html.erb
<%
  @back_button ||= root_path
%>

<h1>All Teachers</h1>

<%= link_to 'Add New Teacher', new_admin_teacher_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Teacher</th>
      <th>Email</th>
      <th>Admin?</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @teachers %>
  </tbody>
</table>

app/views/admin/teachers/new.html.erb
<%
  @back_button ||= root_path
%>

<h1>Create New Teacher</h1>

<%= render "form", locals: { form_path: admin_teachers_path, method: :post }%>

<%= link_to 'Back to list', admin_teachers_path, class: 'btn btn-secondary' %>

app/views/documents/_document.html.erb
<li id="<%= dom_id(document) %>">
  <div class="accordion">
    <details name="my_accordion">
      <summary>
        <%= document.title %>
      </summary>
      <p class="text-sm pbe-4">
        <span> - Added on <%= document.created_at.strftime("%B %d, %Y at %I:%M %p") %></span>
        <div class="flex gap">
          <div class="input input--actor flex items-center gap" data-controller="copyable-input">
            <input type="text" name="copyable_input" id="copyable_input" value="<%= "#{ENV["DEFAULT_APP_URL"]}#{document.shareable_url}" %>" readonly="readonly" data-copyable-input-target="input" />
            <button class="btn btn--plain" data-action="copyable-input#copy">
              <img aria-hidden="true" data-copyable-input-target="copyIcon" hidden="hidden" width="20" height="20" />
              <img aria-hidden="true" data-copyable-input-target="successIcon" hidden="hidden" width="20" height="20" />
              <span class="sr-only">Copy to clipboard</span>
            </button>
          </div>
          <%= link_to "View", document_path(document), class: "btn btn--secondary" %>
          <%= form_with(model: document, url: document_path(document), method: :delete, data: { turbo_action: 'replace', turbo_confirm: 'Are you sure you want to delete this document?' }) do |form| %>
            <%= form.submit "Delete", class: "delete-button btn btn--negative", data: { turbo_stream: turbo_stream.remove(dom_id(document)) } %>
          <% end %>
        </div>
      </p>
    </details>
  </div>
  <hr class="mb-4 border-dark">
</li>

app/views/documents/_form.html.erb
<%= form_with model: model, url: documents_path, class: "card flex flex-col gap", data: { turbo: true } do |f| %>
  <div class="flex flex-col gap-half">
    <h1 class="text-2xl font-semibold leading-none">Upload a Document</h1>
    <p class="text-sm text-subtle">Add documents to view and share.</p>
  </div>
  <div class="flex flex-col gap mb-2">
    <div class="flex flex-col gap-half">
      <%= f.label :title %>
      <%= f.text_field :title, class: "input" %>
    </div>
    <div class="flex flex-col gap-half">
      <%= f.label :file %>
      <%= f.file_field :file, class: "input" %>
    </div>
    <div class="flex flex-col gap-half">
      <%= f.submit "Upload", class: "btn btn--secondary" %>
    </div>
  </div>
<% end %>

app/views/documents/create.turbo_stream.erb
<turbo-stream action="replace" target="upload_document">
  <template>
    <%= render partial: "documents/form", locals: { model: Document.new }, formats: [:html] %>
  </template>
</turbo-stream>

<turbo-stream action="prepend" target="documents_list">
  <template>
    <%= render partial: "documents/document", locals: { document: @document }, formats: [:html] %>
  </template>
</turbo-stream>

<%= turbo_stream.replace "flash_messages", partial: "layouts/flash_messages" %>

app/views/documents/show.html.erb
<div class="card flex flex-col">
  <div class="flex flex-col gap-half">
    <h1 class="text-2xl font-semibold leading-none"><%= @document.title %></h1>
    <p class="text-sm text-subtle prose"><%= raw @document.render_html %></p>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, message| %>
  <div popover class="flash flash--extended" style="--flash-position: 1rem;" data-controller="element-removal" data-action="animationend->element-removal#remove" role="<%= key %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Doc Share" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="color-scheme" content="light only">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="header-layout">
    <header id="header">
      <div class="container">
        <h1 class="font-bold text-2xl">Doc Share</h1>
      </div>
      <%= render "shared/navbar", back_button: @back_button %>
      <div id="flash_messages">
        <%= render "layouts/flash_messages" %>
      </div>
    </header>

    <main id="main">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="flex items-center gap">
  <div>
    <%= link_to "Home", root_path %>
  </div>
  <% if defined?(current_teacher) && current_teacher&.admin? %>
    <hr class="mi-2 border-is border-dark" style="block-size: 1.5rem" aria-hidden="true">
    <div>
        <%= link_to "Admin Dashboard", admin_teachers_path %>
    </div>
  <% end %>
  <hr class="mi-2 border-is border-dark" style="block-size: 1.5rem" aria-hidden="true">
  <div>
    <% if teacher_signed_in? %>
      <%= button_to "Logout", destroy_teacher_session_path, method: :delete, data: { turbo: true }, class: "btn" %>
    <% end %>
  </div>
</div>

app/views/teachers/dashboard.html.erb
<div class="flex flex-col gap-half"
  <h1 class="text-2xl font-semibold leading-none">Welcome, <%= current_teacher.email %></h1>

  <turbo-frame id="upload_document">
    <%= render partial: "documents/form", locals: { model: @document } %>
  </turbo-frame>

  <div class="flex flex-col gap">
    <h1 class="text-2xl font-semibold leading-none">Your Documents</h1>
  </div>
  <ul id="documents_list">
    <% @documents.each do |document| %>
      <%= render partial: "documents/document", locals: { document: document } %>
    <% end %>
  </ul>
</div>